#配置项目端口和根路径
server:
  port: 8080
  servlet:
    context-path: /boot

spring:
  thymeleaf:
    cache: false
  #配置项目的数据库链接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///aiface?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level: warn
    file: ./boot.log
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #oss相关配置
oss:
  accessKeyId: LTAIqnevufzufutK
  accessKeySecret: 6xMPcRlAArDdYQdB3TbCzr0rpVGABR
  bucketFace: ai-face-yyj
  bucketDetail: ai-face-detail-yyj
  endPoint: http://oss-cn-hangzhou.aliyuncs.com